# Generated by Django 4.1 on 2022-08-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Livros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=15)),
                ("autor", models.CharField(max_length=50)),
                ("data_cadastro", models.DateField()),
                ("disponivel", models.BooleanField(default=True)),
                ("volume", models.DecimalField(decimal_places=3, max_digits=10)),
                ("edicao", models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
