# Generated by Django 4.1 on 2022-08-08 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="livros", options={"verbose_name": "Livro"},),
        migrations.AlterField(
            model_name="livros",
            name="data_cadastro",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="livros",
            name="edicao",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name="livros",
            name="volume",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10),
        ),
    ]
