# Generated by Django 4.1 on 2022-08-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0002_alter_livros_options_alter_livros_data_cadastro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livros",
            name="edicao",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="livros",
            name="volume",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=10, null=True
            ),
        ),
    ]
