# Generated by Django 4.1 on 2022-08-11 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0003_alter_livros_edicao_alter_livros_volume"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=40)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="livros",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="livro.categoria",
            ),
            preserve_default=False,
        ),
    ]
