# Generated by Django 4.1.1 on 2022-10-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_product_descri_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='margonha',
            field=models.URLField(null=True),
        ),
    ]
