# Generated by Django 4.1.1 on 2022-10-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('coauthor', models.CharField(blank=True, max_length=100)),
                ('edition', models.IntegerField()),
                ('state', models.CharField(choices=[('Bem conservado', 'Bem conservado'), ('Conservado', 'Conservado'), ('Pouco conservado', 'Pouco conservado')], max_length=30, null=True)),
                ('type', models.CharField(choices=[('Livro', 'Livro'), ('Cópia', 'Cópia')], max_length=30, null=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
