# Generated by Django 4.1.1 on 2022-10-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0002_rename_author_livros_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='state',
            new_name='Estado',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='data',
        ),
        migrations.AlterField(
            model_name='livros',
            name='Edicao',
            field=models.IntegerField(verbose_name='Edição'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='Titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
