# Generated by Django 4.1.1 on 2022-10-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0003_rename_state_livros_estado_remove_livros_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='Codigo',
            field=models.CharField(max_length=20, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='livros',
            name='Data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='Volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='Nome',
            field=models.CharField(max_length=100),
        ),
    ]
