# Generated by Django 4.1.1 on 2022-10-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0004_livros_codigo_livros_data_livros_volume_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livros',
            new_name='Cadastro_de_Livros',
        ),
    ]
