# Generated by Django 4.1.1 on 2022-10-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0005_rename_livros_cadastro_de_livros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadastro_de_Livros',
            new_name='Livro',
        ),
    ]
